### ISSUE TITLE
分享 V2EX 的回复

### ISSUE THREAD

**Issue by aprilorange** [aprilorange/light-bulb#4]
比如：

![image](https://cloud.githubusercontent.com/assets/8784712/9005611/21eb630a-37b2-11e5-9490-f1c9e58448a4.png)

我很想分享第 80 楼到微博，并且单独为这个回复生成一个页面让点击过来的人直接看到，或者以插件的形式修改 V2EX 该话题页面的显示效果。

**Comment by sciooga** [comment]
https://www.v2ex.com/t/209889?p=1#r_2283734

**Comment by aprilorange** [comment]
@sciooga 好吧，我忘了可以这样..... :sob:

**Comment by sciooga** [comment]
别忘了带上页码哦，不然页码不对锚点就失效了

**Comment by aprilorange** [comment]
@sciooga 感谢证明这个想法是无意义的 XD
